<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260701091010 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE folder (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ECA209CD7E3C61F9 ON folder (owner_id)');
        $this->addSql('CREATE TABLE folder_snippet (folder_id INT NOT NULL, snippet_id INT NOT NULL, PRIMARY KEY (folder_id, snippet_id))');
        $this->addSql('CREATE INDEX IDX_2F9FE0A6162CB942 ON folder_snippet (folder_id)');
        $this->addSql('CREATE INDEX IDX_2F9FE0A66E34B975 ON folder_snippet (snippet_id)');
        $this->addSql('CREATE TABLE snippet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, code TEXT NOT NULL, description TEXT DEFAULT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_961C8CD57E3C61F9 ON snippet (owner_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE folder ADD CONSTRAINT FK_ECA209CD7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE folder_snippet ADD CONSTRAINT FK_2F9FE0A6162CB942 FOREIGN KEY (folder_id) REFERENCES folder (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE folder_snippet ADD CONSTRAINT FK_2F9FE0A66E34B975 FOREIGN KEY (snippet_id) REFERENCES snippet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE snippet ADD CONSTRAINT FK_961C8CD57E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE folder DROP CONSTRAINT FK_ECA209CD7E3C61F9');
        $this->addSql('ALTER TABLE folder_snippet DROP CONSTRAINT FK_2F9FE0A6162CB942');
        $this->addSql('ALTER TABLE folder_snippet DROP CONSTRAINT FK_2F9FE0A66E34B975');
        $this->addSql('ALTER TABLE snippet DROP CONSTRAINT FK_961C8CD57E3C61F9');
        $this->addSql('DROP TABLE folder');
        $this->addSql('DROP TABLE folder_snippet');
        $this->addSql('DROP TABLE snippet');
        $this->addSql('DROP TABLE "user"');
    }
}
